
---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.4.1
  creationTimestamp: null
  name: workflows.tinkerbell.org
spec:
  group: tinkerbell.org
  names:
    categories:
    - tinkerbell
    kind: Workflow
    listKind: WorkflowList
    plural: workflows
    singular: workflow
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Workflow is the Schema for the Workflows API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: WorkflowSpec defines the desired state of Workflow.
            properties:
              hardwareRef:
                description: Name of the Hardware associated with this workflow.
                type: string
              templateRef:
                description: Name of the Template associated with this workflow.
                type: string
            type: object
          status:
            description: WorkflowStatus defines the observed state of Workflow.
            properties:
              actions:
                description: Actions are the actions for this Workflow.
                items:
                  description: Action represents a workflow action.
                  properties:
                    command:
                      items:
                        type: string
                      type: array
                    environment:
                      items:
                        type: string
                      type: array
                    image:
                      type: string
                    name:
                      type: string
                    on_failure:
                      items:
                        type: string
                      type: array
                    on_timeout:
                      items:
                        type: string
                      type: array
                    task_name:
                      type: string
                    timeout:
                      format: int64
                      type: integer
                    volumes:
                      items:
                        type: string
                      type: array
                    worker_id:
                      type: string
                  type: object
                type: array
              data:
                description: Data is the populated Workflow Data in Tinkerbell.
                type: string
              events:
                description: Events are events for this Workflow.
                items:
                  description: Event represents a workflow event.
                  properties:
                    action_name:
                      type: string
                    action_status:
                      type: string
                    created_at:
                      format: date-time
                      type: string
                    message:
                      type: string
                    seconds:
                      format: int64
                      type: integer
                    task_name:
                      type: string
                    worker_id:
                      type: string
                  type: object
                type: array
              metadata:
                description: Metadata is the metadata stored in Tinkerbell.
                type: string
              state:
                description: State is the state of the workflow in Tinkerbell.
                type: string
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
