---
apiVersion: apiextensions.k8s.io/v1
kind: CustomResourceDefinition
metadata:
  annotations:
    controller-gen.kubebuilder.io/version: v0.8.0
  creationTimestamp: null
  name: hardware.tinkerbell.org
spec:
  group: tinkerbell.org
  names:
    categories:
    - tinkerbell
    kind: Hardware
    listKind: HardwareList
    plural: hardware
    singular: hardware
  scope: Cluster
  versions:
  - name: v1alpha1
    schema:
      openAPIV3Schema:
        description: Hardware is the Schema for the Hardware API.
        properties:
          apiVersion:
            description: 'APIVersion defines the versioned schema of this representation
              of an object. Servers should convert recognized schemas to the latest
              internal value, and may reject unrecognized values. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#resources'
            type: string
          kind:
            description: 'Kind is a string value representing the REST resource this
              object represents. Servers may infer this from the endpoint the client
              submits requests to. Cannot be updated. In CamelCase. More info: https://git.k8s.io/community/contributors/devel/sig-architecture/api-conventions.md#types-kinds'
            type: string
          metadata:
            type: object
          spec:
            description: HardwareSpec defines the desired state of Hardware.
            properties:
              id:
                description: ID is the ID of the hardware in Tinkerbell
                minLength: 1
                type: string
              userData:
                description: UserData is the user data to configure in the hardware's
                  metadata
                type: string
            required:
            - id
            type: object
          status:
            description: HardwareStatus defines the observed state of Hardware.
            properties:
              disks:
                items:
                  description: Disk represents a disk device for Tinkerbell Hardware.
                  properties:
                    device:
                      type: string
                  type: object
                type: array
              interfaces:
                items:
                  description: Interface represents a network interface configuration
                    for Hardware.
                  properties:
                    dhcp:
                      description: DHCP configuration.
                      properties:
                        arch:
                          type: string
                        hostname:
                          type: string
                        iface_name:
                          type: string
                        ip:
                          description: IP configuration.
                          properties:
                            address:
                              type: string
                            family:
                              format: int64
                              type: integer
                            gateway:
                              type: string
                            netmask:
                              type: string
                          type: object
                        lease_time:
                          format: int64
                          type: integer
                        mac:
                          type: string
                        name_servers:
                          items:
                            type: string
                          type: array
                        time_servers:
                          items:
                            type: string
                          type: array
                        uefi:
                          type: boolean
                      type: object
                    netboot:
                      description: Netboot configuration.
                      properties:
                        allowPXE:
                          type: boolean
                        allowWorkflow:
                          type: boolean
                        ipxe:
                          description: IPXE configuration.
                          properties:
                            contents:
                              type: string
                            url:
                              type: string
                          type: object
                        osie:
                          description: OSIE configuration.
                          properties:
                            baseURL:
                              type: string
                            initrd:
                              type: string
                            kernel:
                              type: string
                          type: object
                      type: object
                  type: object
                type: array
              state:
                description: HardwareState represents the hardware state.
                type: string
              tinkMetadata:
                type: string
              tinkVersion:
                format: int64
                type: integer
            type: object
        type: object
    served: true
    storage: true
    subresources:
      status: {}
status:
  acceptedNames:
    kind: ""
    plural: ""
  conditions: []
  storedVersions: []
